#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 117
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 75
#define ALIAS_COUNT 0
#define TOKEN_COUNT 48
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_POUNDtarget = 2,
  anon_sym_SEMI = 3,
  anon_sym_LF = 4,
  anon_sym_EQ = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_COMMA = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_STAR = 11,
  anon_sym_PLUS = 12,
  anon_sym_SLASH = 13,
  anon_sym_DASH = 14,
  anon_sym_PERCENT = 15,
  anon_sym_PIPE = 16,
  anon_sym_AMP = 17,
  anon_sym_GT_GT = 18,
  anon_sym_LT_LT = 19,
  anon_sym_u8 = 20,
  anon_sym_u16 = 21,
  anon_sym_i8 = 22,
  anon_sym_b1 = 23,
  anon_sym_str = 24,
  anon_sym_le = 25,
  anon_sym_be = 26,
  sym_pointer = 27,
  anon_sym_COLON = 28,
  anon_sym_ADD = 29,
  anon_sym_JMP = 30,
  anon_sym_BNC = 31,
  anon_sym_MOV = 32,
  sym_hlt_statement = 33,
  anon_sym_DOLLAR = 34,
  aux_sym_register_identifier_token1 = 35,
  aux_sym_register_identifier_token2 = 36,
  anon_sym_X = 37,
  anon_sym_Y = 38,
  anon_sym_F = 39,
  anon_sym_SPL = 40,
  anon_sym_SPH = 41,
  sym_decimal = 42,
  anon_sym_DQUOTE = 43,
  aux_sym_string_token1 = 44,
  aux_sym_string_token2 = 45,
  sym_line_comment = 46,
  sym_block_comment = 47,
  sym_source_file = 48,
  sym_target_declaration = 49,
  sym__declaration = 50,
  sym_variable_declaration = 51,
  sym_array_declaration = 52,
  sym__expression = 53,
  sym_expression = 54,
  sym_binary_expression = 55,
  sym__type = 56,
  sym_normal_type = 57,
  sym_endian = 58,
  sym__value = 59,
  sym_function_declaration = 60,
  sym__statement = 61,
  sym_add_statement = 62,
  sym_jmp_statement = 63,
  sym_bnc_statement = 64,
  sym_mov_statement = 65,
  sym_statement_parameter = 66,
  sym_register = 67,
  sym_register_identifier = 68,
  sym_value = 69,
  sym_string = 70,
  aux_sym_source_file_repeat1 = 71,
  aux_sym_array_declaration_repeat1 = 72,
  aux_sym_function_declaration_repeat1 = 73,
  aux_sym_string_repeat1 = 74,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_POUNDtarget] = "#target",
  [anon_sym_SEMI] = ";",
  [anon_sym_LF] = "\n",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH] = "-",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_i8] = "i8",
  [anon_sym_b1] = "b1",
  [anon_sym_str] = "str",
  [anon_sym_le] = "le",
  [anon_sym_be] = "be",
  [sym_pointer] = "pointer",
  [anon_sym_COLON] = ":",
  [anon_sym_ADD] = "ADD",
  [anon_sym_JMP] = "JMP",
  [anon_sym_BNC] = "BNC",
  [anon_sym_MOV] = "MOV",
  [sym_hlt_statement] = "hlt_statement",
  [anon_sym_DOLLAR] = "$",
  [aux_sym_register_identifier_token1] = "register_identifier_token1",
  [aux_sym_register_identifier_token2] = "register_identifier_token2",
  [anon_sym_X] = "X",
  [anon_sym_Y] = "Y",
  [anon_sym_F] = "F",
  [anon_sym_SPL] = "SPL",
  [anon_sym_SPH] = "SPH",
  [sym_decimal] = "decimal",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "escape_sequence",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_target_declaration] = "target_declaration",
  [sym__declaration] = "_declaration",
  [sym_variable_declaration] = "variable_declaration",
  [sym_array_declaration] = "array_declaration",
  [sym__expression] = "_expression",
  [sym_expression] = "expression",
  [sym_binary_expression] = "binary_expression",
  [sym__type] = "_type",
  [sym_normal_type] = "normal_type",
  [sym_endian] = "endian",
  [sym__value] = "_value",
  [sym_function_declaration] = "function_declaration",
  [sym__statement] = "_statement",
  [sym_add_statement] = "add_statement",
  [sym_jmp_statement] = "jmp_statement",
  [sym_bnc_statement] = "bnc_statement",
  [sym_mov_statement] = "mov_statement",
  [sym_statement_parameter] = "statement_parameter",
  [sym_register] = "register",
  [sym_register_identifier] = "register_identifier",
  [sym_value] = "value",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_declaration_repeat1] = "array_declaration_repeat1",
  [aux_sym_function_declaration_repeat1] = "function_declaration_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_POUNDtarget] = anon_sym_POUNDtarget,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_b1] = anon_sym_b1,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_le] = anon_sym_le,
  [anon_sym_be] = anon_sym_be,
  [sym_pointer] = sym_pointer,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_ADD] = anon_sym_ADD,
  [anon_sym_JMP] = anon_sym_JMP,
  [anon_sym_BNC] = anon_sym_BNC,
  [anon_sym_MOV] = anon_sym_MOV,
  [sym_hlt_statement] = sym_hlt_statement,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym_register_identifier_token1] = aux_sym_register_identifier_token1,
  [aux_sym_register_identifier_token2] = aux_sym_register_identifier_token2,
  [anon_sym_X] = anon_sym_X,
  [anon_sym_Y] = anon_sym_Y,
  [anon_sym_F] = anon_sym_F,
  [anon_sym_SPL] = anon_sym_SPL,
  [anon_sym_SPH] = anon_sym_SPH,
  [sym_decimal] = sym_decimal,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_target_declaration] = sym_target_declaration,
  [sym__declaration] = sym__declaration,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_array_declaration] = sym_array_declaration,
  [sym__expression] = sym__expression,
  [sym_expression] = sym_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym__type] = sym__type,
  [sym_normal_type] = sym_normal_type,
  [sym_endian] = sym_endian,
  [sym__value] = sym__value,
  [sym_function_declaration] = sym_function_declaration,
  [sym__statement] = sym__statement,
  [sym_add_statement] = sym_add_statement,
  [sym_jmp_statement] = sym_jmp_statement,
  [sym_bnc_statement] = sym_bnc_statement,
  [sym_mov_statement] = sym_mov_statement,
  [sym_statement_parameter] = sym_statement_parameter,
  [sym_register] = sym_register,
  [sym_register_identifier] = sym_register_identifier,
  [sym_value] = sym_value,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_declaration_repeat1] = aux_sym_array_declaration_repeat1,
  [aux_sym_function_declaration_repeat1] = aux_sym_function_declaration_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDtarget] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_le] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_be] = {
    .visible = true,
    .named = false,
  },
  [sym_pointer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ADD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_JMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BNC] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MOV] = {
    .visible = true,
    .named = false,
  },
  [sym_hlt_statement] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_register_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_register_identifier_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Y] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPH] = {
    .visible = true,
    .named = false,
  },
  [sym_decimal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_target_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_array_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_normal_type] = {
    .visible = true,
    .named = true,
  },
  [sym_endian] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_add_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_jmp_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_bnc_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_mov_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [sym_register_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 20,
  [23] = 18,
  [24] = 24,
  [25] = 19,
  [26] = 16,
  [27] = 17,
  [28] = 12,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 31,
  [33] = 33,
  [34] = 34,
  [35] = 34,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 43,
  [45] = 37,
  [46] = 39,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 49,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 63,
  [71] = 68,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 78,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 74,
  [95] = 77,
  [96] = 96,
  [97] = 97,
  [98] = 79,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '"', 69,
        '#', 26,
        '$', 57,
        '%', 46,
        '&', 48,
        '(', 40,
        ')', 41,
        '*', 42,
        '+', 43,
        ',', 39,
        '-', 45,
        '/', 44,
        ':', 51,
        ';', 34,
        '<', 8,
        '=', 36,
        '>', 9,
        'A', 61,
        'B', 62,
        'C', 60,
        'F', 65,
        'H', 14,
        'J', 15,
        'M', 17,
        'S', 18,
        'X', 63,
        'Y', 64,
        '[', 37,
        '\\', 28,
        ']', 38,
        '|', 47,
        '8', 68,
        '9', 68,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(30);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(59);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '/') ADVANCE(70);
      if (lookahead == '\\') ADVANCE(28);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(1);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(78);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(79);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'F') ADVANCE(65);
      if (lookahead == 'S') ADVANCE(18);
      if (lookahead == 'X') ADVANCE(63);
      if (lookahead == 'Y') ADVANCE(64);
      if (('A' <= lookahead && lookahead <= 'C')) ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(58);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 8:
      if (lookahead == '<') ADVANCE(50);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(49);
      END_STATE();
    case 10:
      if (lookahead == 'C') ADVANCE(54);
      END_STATE();
    case 11:
      if (lookahead == 'D') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'D') ADVANCE(52);
      END_STATE();
    case 13:
      if (lookahead == 'H') ADVANCE(67);
      if (lookahead == 'L') ADVANCE(66);
      END_STATE();
    case 14:
      if (lookahead == 'L') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'M') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'N') ADVANCE(10);
      END_STATE();
    case 17:
      if (lookahead == 'O') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'P') ADVANCE(13);
      END_STATE();
    case 19:
      if (lookahead == 'P') ADVANCE(53);
      END_STATE();
    case 20:
      if (lookahead == 'T') ADVANCE(56);
      END_STATE();
    case 21:
      if (lookahead == 'V') ADVANCE(55);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'g') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 28:
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(76);
      END_STATE();
    case 29:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 35,
        '%', 46,
        '&', 48,
        '*', 42,
        '+', 43,
        ',', 39,
        '-', 45,
        '/', 44,
        ';', 34,
        '<', 8,
        '>', 9,
        'A', 11,
        'B', 16,
        'H', 14,
        'J', 15,
        'M', 17,
        '|', 47,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(29);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 30:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '"', 69,
        '#', 26,
        '$', 57,
        '%', 46,
        '&', 48,
        '(', 40,
        ')', 41,
        '*', 42,
        '+', 43,
        ',', 39,
        '-', 45,
        '/', 44,
        ':', 51,
        ';', 34,
        '<', 8,
        '=', 36,
        '>', 9,
        'A', 61,
        'B', 62,
        'C', 60,
        'F', 65,
        'H', 14,
        'J', 15,
        'M', 17,
        'S', 18,
        'X', 63,
        'Y', 64,
        '[', 37,
        ']', 38,
        '|', 47,
        '8', 68,
        '9', 68,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(30);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(59);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '"', 69,
        '(', 40,
        '/', 3,
        'A', 11,
        'B', 16,
        'H', 14,
        'J', 15,
        'M', 17,
        ']', 38,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_POUNDtarget);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(78);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_ADD);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_JMP);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BNC);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_MOV);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_hlt_statement);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_register_identifier_token1);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_register_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_register_identifier_token2);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_register_identifier_token2);
      if (lookahead == 'D') ADVANCE(12);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_register_identifier_token2);
      if (lookahead == 'N') ADVANCE(10);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_X);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_Y);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_F);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SPL);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_SPH);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(72);
      if (lookahead == '/') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(75);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(71);
      if (lookahead == '/') ADVANCE(75);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(71);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(70);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\f' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(75);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\r' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == 'p') ADVANCE(4);
      if (lookahead == 's') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '1') ADVANCE(7);
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '8') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == '1') ADVANCE(13);
      if (lookahead == '8') ADVANCE(14);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_b1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_be);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_le);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == '6') ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_pointer);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 31},
  [3] = {.lex_state = 31},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 29},
  [9] = {.lex_state = 29},
  [10] = {.lex_state = 29},
  [11] = {.lex_state = 29},
  [12] = {.lex_state = 29},
  [13] = {.lex_state = 31},
  [14] = {.lex_state = 29},
  [15] = {.lex_state = 31},
  [16] = {.lex_state = 29},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 29},
  [19] = {.lex_state = 29},
  [20] = {.lex_state = 29},
  [21] = {.lex_state = 31},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 29},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 31},
  [34] = {.lex_state = 31},
  [35] = {.lex_state = 31},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 31},
  [38] = {.lex_state = 31},
  [39] = {.lex_state = 31},
  [40] = {.lex_state = 31},
  [41] = {.lex_state = 31},
  [42] = {.lex_state = 31},
  [43] = {.lex_state = 31},
  [44] = {.lex_state = 31},
  [45] = {.lex_state = 31},
  [46] = {.lex_state = 31},
  [47] = {.lex_state = 29},
  [48] = {.lex_state = 29},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 29},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 29},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 29},
  [73] = {.lex_state = 29},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 29},
  [81] = {.lex_state = 29},
  [82] = {.lex_state = 29},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 29},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 29},
  [87] = {.lex_state = 29},
  [88] = {.lex_state = 29},
  [89] = {.lex_state = 31},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 29},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 29},
  [95] = {.lex_state = 29},
  [96] = {.lex_state = 29},
  [97] = {.lex_state = 29},
  [98] = {.lex_state = 29},
  [99] = {.lex_state = 29},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_POUNDtarget] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_b1] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_le] = ACTIONS(1),
    [anon_sym_be] = ACTIONS(1),
    [sym_pointer] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_ADD] = ACTIONS(1),
    [anon_sym_JMP] = ACTIONS(1),
    [anon_sym_BNC] = ACTIONS(1),
    [anon_sym_MOV] = ACTIONS(1),
    [sym_hlt_statement] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [aux_sym_register_identifier_token1] = ACTIONS(1),
    [aux_sym_register_identifier_token2] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [anon_sym_Y] = ACTIONS(1),
    [anon_sym_F] = ACTIONS(1),
    [anon_sym_SPL] = ACTIONS(1),
    [anon_sym_SPH] = ACTIONS(1),
    [sym_decimal] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(115),
    [sym_target_declaration] = STATE(4),
    [sym__declaration] = STATE(5),
    [sym_variable_declaration] = STATE(82),
    [sym_array_declaration] = STATE(82),
    [sym__type] = STATE(113),
    [sym_normal_type] = STATE(56),
    [sym_function_declaration] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_POUNDtarget] = ACTIONS(9),
    [anon_sym_u8] = ACTIONS(11),
    [anon_sym_u16] = ACTIONS(11),
    [anon_sym_i8] = ACTIONS(11),
    [anon_sym_b1] = ACTIONS(11),
    [anon_sym_str] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_ADD,
    ACTIONS(19), 1,
      anon_sym_JMP,
    ACTIONS(21), 1,
      anon_sym_BNC,
    ACTIONS(23), 1,
      anon_sym_MOV,
    ACTIONS(25), 1,
      sym_hlt_statement,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(3), 2,
      sym__statement,
      aux_sym_function_declaration_repeat1,
    STATE(99), 4,
      sym_add_statement,
      sym_jmp_statement,
      sym_bnc_statement,
      sym_mov_statement,
    ACTIONS(15), 6,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      sym_identifier,
  [41] = 10,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_ADD,
    ACTIONS(34), 1,
      anon_sym_JMP,
    ACTIONS(37), 1,
      anon_sym_BNC,
    ACTIONS(40), 1,
      anon_sym_MOV,
    ACTIONS(43), 1,
      sym_hlt_statement,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(3), 2,
      sym__statement,
      aux_sym_function_declaration_repeat1,
    STATE(99), 4,
      sym_add_statement,
      sym_jmp_statement,
      sym_bnc_statement,
      sym_mov_statement,
    ACTIONS(29), 6,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      sym_identifier,
  [82] = 8,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    STATE(56), 1,
      sym_normal_type,
    STATE(113), 1,
      sym__type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(82), 2,
      sym_variable_declaration,
      sym_array_declaration,
    STATE(6), 3,
      sym__declaration,
      sym_function_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 5,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
  [115] = 8,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    STATE(56), 1,
      sym_normal_type,
    STATE(113), 1,
      sym__type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(82), 2,
      sym_variable_declaration,
      sym_array_declaration,
    STATE(7), 3,
      sym__declaration,
      sym_function_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 5,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
  [148] = 8,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    STATE(56), 1,
      sym_normal_type,
    STATE(113), 1,
      sym__type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(82), 2,
      sym_variable_declaration,
      sym_array_declaration,
    STATE(7), 3,
      sym__declaration,
      sym_function_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 5,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
  [181] = 8,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      sym_identifier,
    STATE(56), 1,
      sym_normal_type,
    STATE(113), 1,
      sym__type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(82), 2,
      sym_variable_declaration,
      sym_array_declaration,
    STATE(7), 3,
      sym__declaration,
      sym_function_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(55), 5,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
  [214] = 7,
    ACTIONS(58), 1,
      anon_sym_SEMI,
    ACTIONS(60), 1,
      anon_sym_LF,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_array_declaration_repeat1,
    ACTIONS(66), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(64), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [244] = 4,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(72), 11,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      anon_sym_ADD,
      anon_sym_JMP,
      anon_sym_BNC,
      anon_sym_MOV,
      sym_hlt_statement,
      sym_identifier,
  [268] = 7,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(76), 1,
      anon_sym_SEMI,
    ACTIONS(78), 1,
      anon_sym_LF,
    STATE(65), 1,
      aux_sym_array_declaration_repeat1,
    ACTIONS(66), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(64), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [298] = 7,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(82), 1,
      anon_sym_LF,
    STATE(72), 1,
      aux_sym_array_declaration_repeat1,
    ACTIONS(66), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(64), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [328] = 3,
    ACTIONS(86), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(84), 11,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [349] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 6,
      ts_builtin_sym_end,
      anon_sym_ADD,
      anon_sym_JMP,
      anon_sym_BNC,
      anon_sym_MOV,
      sym_hlt_statement,
    ACTIONS(72), 6,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      sym_identifier,
  [370] = 5,
    ACTIONS(90), 1,
      anon_sym_LF,
    ACTIONS(66), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(88), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(64), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [395] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      anon_sym_ADD,
      anon_sym_JMP,
      anon_sym_BNC,
      anon_sym_MOV,
      sym_hlt_statement,
    ACTIONS(94), 6,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      sym_identifier,
  [416] = 3,
    ACTIONS(98), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(96), 11,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [437] = 4,
    ACTIONS(102), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(100), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(64), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [460] = 3,
    ACTIONS(106), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(104), 11,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [481] = 3,
    ACTIONS(102), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(100), 11,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [502] = 3,
    ACTIONS(110), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 11,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [523] = 8,
    ACTIONS(17), 1,
      anon_sym_ADD,
    ACTIONS(19), 1,
      anon_sym_JMP,
    ACTIONS(21), 1,
      anon_sym_BNC,
    ACTIONS(23), 1,
      anon_sym_MOV,
    ACTIONS(25), 1,
      sym_hlt_statement,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(2), 2,
      sym__statement,
      aux_sym_function_declaration_repeat1,
    STATE(99), 4,
      sym_add_statement,
      sym_jmp_statement,
      sym_bnc_statement,
      sym_mov_statement,
  [553] = 3,
    ACTIONS(108), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(110), 10,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [573] = 3,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(106), 10,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [593] = 5,
    ACTIONS(112), 1,
      anon_sym_SEMI,
    ACTIONS(114), 1,
      anon_sym_LF,
    ACTIONS(66), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(64), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [617] = 3,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(102), 10,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [637] = 3,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(98), 10,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [657] = 4,
    ACTIONS(118), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(102), 4,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(116), 6,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [679] = 3,
    ACTIONS(84), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 10,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [699] = 4,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    ACTIONS(124), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(122), 8,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [720] = 4,
    ACTIONS(124), 1,
      anon_sym_SLASH,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(122), 8,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [741] = 5,
    ACTIONS(118), 1,
      anon_sym_SLASH,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(130), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(116), 6,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [764] = 5,
    ACTIONS(118), 1,
      anon_sym_SLASH,
    ACTIONS(132), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(130), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(116), 6,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [787] = 6,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 2,
      sym_decimal,
      sym_identifier,
    STATE(24), 2,
      sym__expression,
      sym_expression,
    STATE(12), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [811] = 6,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 2,
      sym_decimal,
      sym_identifier,
    STATE(19), 2,
      sym__expression,
      sym_expression,
    STATE(12), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [835] = 6,
    ACTIONS(142), 1,
      anon_sym_LPAREN,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(140), 2,
      sym_decimal,
      sym_identifier,
    STATE(25), 2,
      sym__expression,
      sym_expression,
    STATE(28), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [859] = 4,
    ACTIONS(118), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(130), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(116), 6,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT_GT,
      anon_sym_LT_LT,
  [879] = 6,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 2,
      sym_decimal,
      sym_identifier,
    STATE(17), 2,
      sym__expression,
      sym_expression,
    STATE(12), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [903] = 6,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 2,
      sym_decimal,
      sym_identifier,
    STATE(10), 2,
      sym__expression,
      sym_expression,
    STATE(12), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [927] = 6,
    ACTIONS(142), 1,
      anon_sym_LPAREN,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(140), 2,
      sym_decimal,
      sym_identifier,
    STATE(32), 2,
      sym__expression,
      sym_expression,
    STATE(28), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [951] = 6,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 2,
      sym_decimal,
      sym_identifier,
    STATE(8), 2,
      sym__expression,
      sym_expression,
    STATE(12), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [975] = 6,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 2,
      sym_decimal,
      sym_identifier,
    STATE(14), 2,
      sym__expression,
      sym_expression,
    STATE(12), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [999] = 6,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 2,
      sym_decimal,
      sym_identifier,
    STATE(11), 2,
      sym__expression,
      sym_expression,
    STATE(12), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [1023] = 7,
    ACTIONS(142), 1,
      anon_sym_LPAREN,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_expression,
    STATE(36), 1,
      sym__expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(140), 2,
      sym_decimal,
      sym_identifier,
    STATE(28), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [1049] = 7,
    ACTIONS(142), 1,
      anon_sym_LPAREN,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      sym_expression,
    STATE(36), 1,
      sym__expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(140), 2,
      sym_decimal,
      sym_identifier,
    STATE(28), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [1075] = 6,
    ACTIONS(142), 1,
      anon_sym_LPAREN,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(140), 2,
      sym_decimal,
      sym_identifier,
    STATE(27), 2,
      sym__expression,
      sym_expression,
    STATE(28), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [1099] = 6,
    ACTIONS(142), 1,
      anon_sym_LPAREN,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(140), 2,
      sym_decimal,
      sym_identifier,
    STATE(31), 2,
      sym__expression,
      sym_expression,
    STATE(28), 3,
      sym_binary_expression,
      sym__value,
      sym_string,
  [1123] = 4,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(150), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(148), 6,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      sym_identifier,
  [1142] = 4,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(154), 6,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      sym_identifier,
  [1161] = 3,
    STATE(77), 1,
      sym_register_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(158), 7,
      aux_sym_register_identifier_token1,
      aux_sym_register_identifier_token2,
      anon_sym_X,
      anon_sym_Y,
      anon_sym_F,
      anon_sym_SPL,
      anon_sym_SPH,
  [1178] = 3,
    STATE(95), 1,
      sym_register_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(160), 7,
      aux_sym_register_identifier_token1,
      aux_sym_register_identifier_token2,
      anon_sym_X,
      anon_sym_Y,
      anon_sym_F,
      anon_sym_SPL,
      anon_sym_SPH,
  [1195] = 3,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(164), 6,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      sym_identifier,
  [1211] = 3,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(154), 6,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      sym_identifier,
  [1227] = 3,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(148), 6,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      sym_identifier,
  [1243] = 3,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(168), 6,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_i8,
      anon_sym_b1,
      anon_sym_str,
      sym_identifier,
  [1259] = 6,
    ACTIONS(170), 1,
      anon_sym_LBRACK,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_DOLLAR,
    STATE(76), 1,
      sym_statement_parameter,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(79), 2,
      sym_register,
      sym_value,
  [1280] = 6,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(178), 1,
      anon_sym_LBRACK,
    ACTIONS(182), 1,
      sym_pointer,
    STATE(92), 1,
      sym_endian,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(180), 2,
      anon_sym_le,
      anon_sym_be,
  [1301] = 6,
    ACTIONS(184), 1,
      anon_sym_LBRACK,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_DOLLAR,
    STATE(91), 1,
      sym_statement_parameter,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(98), 2,
      sym_register,
      sym_value,
  [1322] = 3,
    ACTIONS(192), 1,
      anon_sym_LBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(190), 4,
      anon_sym_le,
      anon_sym_be,
      sym_pointer,
      sym_identifier,
  [1336] = 5,
    ACTIONS(170), 1,
      anon_sym_LBRACK,
    ACTIONS(174), 1,
      anon_sym_DOLLAR,
    STATE(55), 1,
      sym_statement_parameter,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(79), 2,
      sym_register,
      sym_value,
  [1354] = 5,
    ACTIONS(170), 1,
      anon_sym_LBRACK,
    ACTIONS(174), 1,
      anon_sym_DOLLAR,
    STATE(57), 1,
      sym_statement_parameter,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(79), 2,
      sym_register,
      sym_value,
  [1372] = 5,
    ACTIONS(170), 1,
      anon_sym_LBRACK,
    ACTIONS(174), 1,
      anon_sym_DOLLAR,
    STATE(75), 1,
      sym_statement_parameter,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(79), 2,
      sym_register,
      sym_value,
  [1390] = 5,
    ACTIONS(184), 1,
      anon_sym_LBRACK,
    ACTIONS(188), 1,
      anon_sym_DOLLAR,
    STATE(88), 1,
      sym_statement_parameter,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(98), 2,
      sym_register,
      sym_value,
  [1408] = 5,
    ACTIONS(194), 1,
      anon_sym_DQUOTE,
    ACTIONS(196), 1,
      aux_sym_string_token1,
    ACTIONS(198), 1,
      aux_sym_string_token2,
    STATE(64), 1,
      aux_sym_string_repeat1,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1425] = 5,
    ACTIONS(200), 1,
      anon_sym_DQUOTE,
    ACTIONS(202), 1,
      aux_sym_string_token1,
    ACTIONS(205), 1,
      aux_sym_string_token2,
    STATE(64), 1,
      aux_sym_string_repeat1,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1442] = 5,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_SEMI,
    ACTIONS(210), 1,
      anon_sym_LF,
    STATE(67), 1,
      aux_sym_array_declaration_repeat1,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1459] = 4,
    ACTIONS(214), 1,
      sym_pointer,
    STATE(107), 1,
      sym_endian,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(212), 2,
      anon_sym_le,
      anon_sym_be,
  [1474] = 5,
    ACTIONS(88), 1,
      anon_sym_SEMI,
    ACTIONS(90), 1,
      anon_sym_LF,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_array_declaration_repeat1,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1491] = 5,
    ACTIONS(219), 1,
      anon_sym_DQUOTE,
    ACTIONS(221), 1,
      aux_sym_string_token1,
    ACTIONS(223), 1,
      aux_sym_string_token2,
    STATE(70), 1,
      aux_sym_string_repeat1,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1508] = 4,
    ACTIONS(225), 1,
      sym_pointer,
    STATE(110), 1,
      sym_endian,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(212), 2,
      anon_sym_le,
      anon_sym_be,
  [1523] = 5,
    ACTIONS(196), 1,
      aux_sym_string_token1,
    ACTIONS(198), 1,
      aux_sym_string_token2,
    ACTIONS(227), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      aux_sym_string_repeat1,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1540] = 5,
    ACTIONS(229), 1,
      anon_sym_DQUOTE,
    ACTIONS(231), 1,
      aux_sym_string_token1,
    ACTIONS(233), 1,
      aux_sym_string_token2,
    STATE(63), 1,
      aux_sym_string_repeat1,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1557] = 5,
    ACTIONS(58), 1,
      anon_sym_SEMI,
    ACTIONS(60), 1,
      anon_sym_LF,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_array_declaration_repeat1,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1574] = 5,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(76), 1,
      anon_sym_SEMI,
    ACTIONS(78), 1,
      anon_sym_LF,
    STATE(67), 1,
      aux_sym_array_declaration_repeat1,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1591] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(235), 3,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
  [1601] = 4,
    ACTIONS(188), 1,
      anon_sym_DOLLAR,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    STATE(84), 1,
      sym_register,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1615] = 4,
    ACTIONS(188), 1,
      anon_sym_DOLLAR,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    STATE(86), 1,
      sym_register,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1629] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(241), 3,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
  [1639] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(243), 3,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
  [1649] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(245), 3,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
  [1659] = 3,
    ACTIONS(247), 1,
      anon_sym_SEMI,
    ACTIONS(249), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1670] = 3,
    ACTIONS(243), 1,
      anon_sym_LF,
    ACTIONS(251), 1,
      anon_sym_SEMI,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1681] = 3,
    ACTIONS(253), 1,
      anon_sym_SEMI,
    ACTIONS(255), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1692] = 3,
    ACTIONS(188), 1,
      anon_sym_DOLLAR,
    STATE(80), 1,
      sym_register,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1703] = 3,
    ACTIONS(257), 1,
      anon_sym_SEMI,
    ACTIONS(259), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1714] = 3,
    ACTIONS(188), 1,
      anon_sym_DOLLAR,
    STATE(84), 1,
      sym_register,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1725] = 3,
    ACTIONS(261), 1,
      anon_sym_SEMI,
    ACTIONS(263), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1736] = 3,
    ACTIONS(265), 1,
      anon_sym_SEMI,
    ACTIONS(267), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1747] = 3,
    ACTIONS(269), 1,
      anon_sym_SEMI,
    ACTIONS(271), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1758] = 3,
    ACTIONS(273), 1,
      anon_sym_RBRACK,
    ACTIONS(275), 1,
      sym_decimal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1769] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(277), 2,
      sym_pointer,
      sym_identifier,
  [1778] = 3,
    ACTIONS(279), 1,
      anon_sym_SEMI,
    ACTIONS(281), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1789] = 3,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(285), 1,
      sym_pointer,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1800] = 3,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    STATE(87), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1811] = 3,
    ACTIONS(235), 1,
      anon_sym_LF,
    ACTIONS(287), 1,
      anon_sym_SEMI,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1822] = 3,
    ACTIONS(241), 1,
      anon_sym_LF,
    ACTIONS(289), 1,
      anon_sym_SEMI,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1833] = 3,
    ACTIONS(291), 1,
      anon_sym_SEMI,
    ACTIONS(293), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1844] = 3,
    ACTIONS(295), 1,
      anon_sym_SEMI,
    ACTIONS(297), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1855] = 3,
    ACTIONS(245), 1,
      anon_sym_LF,
    ACTIONS(299), 1,
      anon_sym_SEMI,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1866] = 3,
    ACTIONS(301), 1,
      anon_sym_SEMI,
    ACTIONS(303), 1,
      anon_sym_LF,
    ACTIONS(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1877] = 2,
    ACTIONS(305), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1885] = 2,
    ACTIONS(307), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1893] = 2,
    ACTIONS(309), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1901] = 2,
    ACTIONS(311), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1909] = 2,
    ACTIONS(313), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1917] = 2,
    ACTIONS(315), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1925] = 2,
    ACTIONS(317), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1933] = 2,
    ACTIONS(225), 1,
      sym_pointer,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1941] = 2,
    ACTIONS(319), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1949] = 2,
    ACTIONS(321), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1957] = 2,
    ACTIONS(323), 1,
      sym_pointer,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1965] = 2,
    ACTIONS(325), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1973] = 2,
    ACTIONS(327), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1981] = 2,
    ACTIONS(329), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1989] = 2,
    ACTIONS(331), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1997] = 2,
    ACTIONS(333), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2005] = 2,
    ACTIONS(335), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 115,
  [SMALL_STATE(6)] = 148,
  [SMALL_STATE(7)] = 181,
  [SMALL_STATE(8)] = 214,
  [SMALL_STATE(9)] = 244,
  [SMALL_STATE(10)] = 268,
  [SMALL_STATE(11)] = 298,
  [SMALL_STATE(12)] = 328,
  [SMALL_STATE(13)] = 349,
  [SMALL_STATE(14)] = 370,
  [SMALL_STATE(15)] = 395,
  [SMALL_STATE(16)] = 416,
  [SMALL_STATE(17)] = 437,
  [SMALL_STATE(18)] = 460,
  [SMALL_STATE(19)] = 481,
  [SMALL_STATE(20)] = 502,
  [SMALL_STATE(21)] = 523,
  [SMALL_STATE(22)] = 553,
  [SMALL_STATE(23)] = 573,
  [SMALL_STATE(24)] = 593,
  [SMALL_STATE(25)] = 617,
  [SMALL_STATE(26)] = 637,
  [SMALL_STATE(27)] = 657,
  [SMALL_STATE(28)] = 679,
  [SMALL_STATE(29)] = 699,
  [SMALL_STATE(30)] = 720,
  [SMALL_STATE(31)] = 741,
  [SMALL_STATE(32)] = 764,
  [SMALL_STATE(33)] = 787,
  [SMALL_STATE(34)] = 811,
  [SMALL_STATE(35)] = 835,
  [SMALL_STATE(36)] = 859,
  [SMALL_STATE(37)] = 879,
  [SMALL_STATE(38)] = 903,
  [SMALL_STATE(39)] = 927,
  [SMALL_STATE(40)] = 951,
  [SMALL_STATE(41)] = 975,
  [SMALL_STATE(42)] = 999,
  [SMALL_STATE(43)] = 1023,
  [SMALL_STATE(44)] = 1049,
  [SMALL_STATE(45)] = 1075,
  [SMALL_STATE(46)] = 1099,
  [SMALL_STATE(47)] = 1123,
  [SMALL_STATE(48)] = 1142,
  [SMALL_STATE(49)] = 1161,
  [SMALL_STATE(50)] = 1178,
  [SMALL_STATE(51)] = 1195,
  [SMALL_STATE(52)] = 1211,
  [SMALL_STATE(53)] = 1227,
  [SMALL_STATE(54)] = 1243,
  [SMALL_STATE(55)] = 1259,
  [SMALL_STATE(56)] = 1280,
  [SMALL_STATE(57)] = 1301,
  [SMALL_STATE(58)] = 1322,
  [SMALL_STATE(59)] = 1336,
  [SMALL_STATE(60)] = 1354,
  [SMALL_STATE(61)] = 1372,
  [SMALL_STATE(62)] = 1390,
  [SMALL_STATE(63)] = 1408,
  [SMALL_STATE(64)] = 1425,
  [SMALL_STATE(65)] = 1442,
  [SMALL_STATE(66)] = 1459,
  [SMALL_STATE(67)] = 1474,
  [SMALL_STATE(68)] = 1491,
  [SMALL_STATE(69)] = 1508,
  [SMALL_STATE(70)] = 1523,
  [SMALL_STATE(71)] = 1540,
  [SMALL_STATE(72)] = 1557,
  [SMALL_STATE(73)] = 1574,
  [SMALL_STATE(74)] = 1591,
  [SMALL_STATE(75)] = 1601,
  [SMALL_STATE(76)] = 1615,
  [SMALL_STATE(77)] = 1629,
  [SMALL_STATE(78)] = 1639,
  [SMALL_STATE(79)] = 1649,
  [SMALL_STATE(80)] = 1659,
  [SMALL_STATE(81)] = 1670,
  [SMALL_STATE(82)] = 1681,
  [SMALL_STATE(83)] = 1692,
  [SMALL_STATE(84)] = 1703,
  [SMALL_STATE(85)] = 1714,
  [SMALL_STATE(86)] = 1725,
  [SMALL_STATE(87)] = 1736,
  [SMALL_STATE(88)] = 1747,
  [SMALL_STATE(89)] = 1758,
  [SMALL_STATE(90)] = 1769,
  [SMALL_STATE(91)] = 1778,
  [SMALL_STATE(92)] = 1789,
  [SMALL_STATE(93)] = 1800,
  [SMALL_STATE(94)] = 1811,
  [SMALL_STATE(95)] = 1822,
  [SMALL_STATE(96)] = 1833,
  [SMALL_STATE(97)] = 1844,
  [SMALL_STATE(98)] = 1855,
  [SMALL_STATE(99)] = 1866,
  [SMALL_STATE(100)] = 1877,
  [SMALL_STATE(101)] = 1885,
  [SMALL_STATE(102)] = 1893,
  [SMALL_STATE(103)] = 1901,
  [SMALL_STATE(104)] = 1909,
  [SMALL_STATE(105)] = 1917,
  [SMALL_STATE(106)] = 1925,
  [SMALL_STATE(107)] = 1933,
  [SMALL_STATE(108)] = 1941,
  [SMALL_STATE(109)] = 1949,
  [SMALL_STATE(110)] = 1957,
  [SMALL_STATE(111)] = 1965,
  [SMALL_STATE(112)] = 1973,
  [SMALL_STATE(113)] = 1981,
  [SMALL_STATE(114)] = 1989,
  [SMALL_STATE(115)] = 1997,
  [SMALL_STATE(116)] = 2005,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 3, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 3, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_declaration_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_declaration, 8, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_declaration, 8, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_declaration, 9, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_declaration, 9, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_declaration, 7, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_declaration, 7, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_declaration_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_declaration_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_declaration, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_target_declaration, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_declaration, 4, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_target_declaration, 4, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_normal_type, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_normal_type, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_declaration, 10, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_declaration, 10, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [216] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_register, 2, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_register_identifier, 1, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_parameter, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_statement, 6, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_statement, 6, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_register_identifier, 1, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_statement, 5, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_statement, 5, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_statement, 4, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_statement, 4, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mov_statement, 4, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mov_statement, 4, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_endian, 1, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mov_statement, 3, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mov_statement, 3, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type, 2, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 3, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_register, 2, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bnc_statement, 2, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bnc_statement, 2, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jmp_statement, 2, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jmp_statement, 2, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_parameter, 1, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 3, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 2, 0, 0),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [333] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_helium(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
